### ISSUE TITLE
Create a release?

### ISSUE THREAD

**Issue by tynril** [thomasliddledba/kubenswin#1]
Hi!

I'd like to add `kubenswin` to [scoop](https://github.com/ScoopInstaller), alongside `kubectxwin` which is already there. To make that possible, a GitHub release for `kubenswin` needs to exist.

Would it be possible to create one?

Thanks.

**Comment by thomasliddledba** [comment]
@tynril 
I apologize for the late response on this.  Yes!  I can create a release.

**Comment by thomasliddledba** [comment]
@tynril - I created a release.

Thanks for using `kubenswin` and `kubectxwin`
